project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Tidyverse"
            file: content/01_journal/01_tidyverse.qmd
          - text: "Chapter 1 Challenge"
            file: content/01_journal/Chapter_1_Challenge.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto
